export { default as baseConfig } from './base.mjs'
export { default as typescriptConfig } from './typescript.mjs'
export { default as reactConfig } from './react.mjs'
export { default as nextConfig } from './next.mjs'
export { default as prettierConfig } from './prettier.mjs'
export { default as hooksConfig } from './hooks.mjs'
export { default as importsConfig } from './imports.mjs'
